apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  labels:
    run: my-nginx
spec:
  ports: 
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
  selector:
    run: my-nginx
