apiVersion: v1
kind: Service
metadata:
  name: exip
  namespace: default
spec:
  type: NodePort
  selector:
    app: nginx0-deployment
  ports:
  - port: 80
    targetPort: 3001
    nodePort: 32001
    protocol: TCP
