apiVersion: apps/v1
kind: Deployment
metadata:
  name: confluence-server
spec:
  selector:
    matchLabels:
      run: confluence-server
  replicas: 1
  template:
    metadata:
      labels:
        run: confluence-server
    spec:
      containers:
      - name: confluence-server
        image: atlassian/confluence-server
        ports:
        - containerPort: 8090
        - containerPort: 8091
