apiVersion: v1
kind: Service
metadata:
  name: confluence-server
  labels:
    run: confluence-server
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30180
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    run: confluence-server
